run:
  concurrency: 8
  deadline: 10m
  tests: false
  timeout: 5m

linters-settings:
  godot:
    capital: true
  govet:
    check-shadowing: true
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    disabled-checks:
      - hugeParam
    enabled-tags:
      - performance
      - experimental
      - diagnostic
      - style
  errcheck:
    check-type-assertions: true
  nakedret:
    l: 25

linters:
  disable-all: true
  enable:
    - asciicheck # Simple linter to check that your code does not contain non-ASCII identifiers.
    - errcheck # Errcheck is a program for checking for unchecked errors in go programs.
    - bodyclose # Checks whether HTTP response body is closed successfully.
    - misspell # Finds commonly misspelled English words in comments.
    - govet # Vet examines Go source code and reports suspicious constructs, such as Printf calls whose arguments do not align with the format string.
    - unconvert # Remove unnecessary type conversions.
    - unused # Checks Go code for unused constants, variables, functions and types.
    - unparam # Reports unused function parameters
    - typecheck # Like the front-end of a Go compiler, parses and type-checks Go code.
    - whitespace # Tool for detection of leading and trailing whitespace.
    - stylecheck # Stylecheck is a replacement for golint.
    - exportloopref # An analyzer that finds exporting pointers for loop variables.
    - goconst # Finds repeated strings that could be replaced by a constant.
    - gocritic # The most opinionated Go source code linter.
    - godot # Check if comments end in a period.
    - gofmt # Gofmt checks whether code was gofmt-ed.
    - goimports # Goimports does everything that gofmt does. Additionally it checks unused imports.
    - revive # Fast, configurable, extensible, flexible, and beautiful linter for Go.
    - gosec # Inspects source code for security problems.
    - gosimple # Linter for Go source code that specializes in simplifying a code.
    - ineffassign # Detects when assignments to existing variables are not used.
    - prealloc # Finds slice declarations that could potentially be preallocated.
    - staticcheck # Staticcheck is a go vet on steroids, applying a ton of static analysis checks.
    - dupl # Tool for code clone detection.
    - nakedret # Finds naked returns in functions greater than a specified function length.
    - gocognit # Computes and checks the cognitive complexity of functions.
    - gocyclo # Computes and checks the cyclomatic complexity of functions.
    - makezero # Finds slice declarations with non-zero initial length.
    - nestif # Reports deeply nested if statements.
    - sqlclosecheck # Checks that sql.Rows and sql.Stmt are closed.
    - lll # Reports long lines.
    - gochecknoglobals # Checks that no global variables exist.
    - gochecknoinits # Checks that no init functions are present in Go code.

issues:
  exclude-rules:
    - linters:
        - lll
      # can't break go:generate into multiple lines
      source: "^//go:generate "
