version: '3.6'

services:

  postgresql:
    image: postgres:15-alpine
    container_name: postgresql
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env/.env
    depends_on:
      - postgresql
    restart: on-failure
    ports:
      - "8080:8080"
    command: server

volumes:
  db-data: