version: '3.6'

services:
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  postgresql:
    image: postgres:15-alpine
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
